source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
ruby '2.4.2'
gem 'rails', '~> 5.1', '>= 5.1.4'
# gem 'rails', '~> 5.0', '>= 5.0.0.1'
gem 'responders', '~> 2.4'
# gem 'haml', '~> 4.0.5'
gem 'haml', '~> 5.0', '>= 5.0.4'
gem 'momentjs-rails'
gem 'moment_timezone-rails', '~> 0.5.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0', '>= 5.0.6'
# gem 'mongoid_paranoia'
# gem added to test features of chartkick
# gem 'active_median', '~> 0.1.0'

# gem 'wisper', '2.0.0'
# gem 'wisper-sidekiq', '~> 0.0.1'
gem 'wisper-celluloid', '~> 0.0.1'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.2', '>= 4.2.2'
gem 'rqrcode_png', '~> 0.1.5'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer','~> 0.12.3', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails', '~> 4.3', '>= 4.3.1'
gem 'time_difference', '~> 0.4.2'

gem 'simple_form', '~> 3.5'

gem 'smarter_csv', '~> 1.1', '>= 1.1.4'

gem 'remotipart', '~> 1.3', '>= 1.3.1'
gem 'backbone-on-rails','~> 1.2.0.0' #ADDED BY KUMAR ABINASH

gem 'auto-session-timeout', '~> 0.9.2'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks', '~> 5.0.1'
gem 'hashie', '~> 3.4', '>= 3.4.6'
gem 'ventable', '~> 1.0'
gem 'wicked_pdf', '~> 1.1'
gem 'wkhtmltopdf-binary-edge', '~> 0.12.3.0' #0.12.3.0 , 0.12.2.1
gem 'carrierwave', '~> 0.11.2'
# gem 'carrierwave-base64','~> 2.6.1'
# gem 'carrierwave-data-uri','~> 0.2.0'
gem 'global', '~> 0.1.2'
gem 'fiscali', '~> 2.4', '>= 2.4.3'
gem 'mongoid-ancestry', '~> 0.4.2'
gem 'inline_svg', '~> 0.11.1'
gem 'erubis', '~> 2.7'

# Mongoid
gem 'bson', '~> 4.2.1'
#gem "mongoid"
gem 'mongoid', '~> 6.2', '>= 6.2.1'
gem 'mongo', '~> 2.4.1'

# gem "bson"
# gem "mongoid"
# gem "moped", github: "mongoid/moped"
# gem 'mongoid-history'

gem 'carrierwave-mongoid', '~> 0.10.0'
gem 'nested_form', '~> 0.3.2'
gem 'apipie-rails', '~> 0.5.4'
# gem 'faker', git: 'https://github.com/stympy/faker'
 gem 'faker', '~> 1.7', '>= 1.7.3'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.6', '>= 2.6.1'

gem 'pry-rails', '~> 0.3.4', :group => :development
group :development, :preprod,:test, :preproduction do
  gem 'rack-mini-profiler', '~> 0.10.1'
  gem 'memory_profiler', '~> 0.9.7'
  gem 'flamegraph', '~> 0.9.5'
  gem 'stackprof', '~> 0.2.10'
  gem 'fast_stack', '~> 0.2.0'
end
gem 'will_paginate', '~> 3.1', '>= 3.1.5'

gem 'data-confirm-modal', '~> 1.3'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', '~> 0.4.2', require: false
end

group :development, :test do
  gem 'letter_opener','~> 1.4.1'
  gem 'rspec-rails', '~> 3.5', '>= 3.5.2'
  gem 'rails-controller-testing'
  gem 'jasmine', '~> 2.5', '>= 2.5.1'
  #for running js with capybara
  gem 'selenium-webdriver', '~> 3.0', '>= 3.0.5'
  gem 'chromedriver-helper', '~> 1.0'
  #for performance testing
  gem 'bullet', '~> 5.5'
  gem 'puma'
  gem 'meta_request', '~> 0.4.0'
  gem 'byebug', '~> 10.0', '>= 10.0.2'
end

group :test do
  # gem 'shoulda-matchers', require: false  #gem was removed by rakesh, because it was buggy
  gem 'factory_girl_rails', '~> 4.8', :require => false
  gem 'capybara', '~> 2.12'
  gem 'guard-rspec', '~> 4.7', '>= 4.7.3'
  gem 'launchy', '~> 2.4', '>= 2.4.3'
  gem 'database_cleaner', '~> 1.5', '>= 1.5.3'
  gem 'state_machines_rspec','~> 0.3.2'
  gem 'rspec-benchmark', '~> 0.3.0'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'simplecov', :require => false
  # gem 'mongoid-rspec', '~> 3.0'     not compatible with mongo 6 "https://github.com/mongoid/mongoid-rspec/issues/169"
end

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1', '>= 3.1.11'
#gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
gem 'unicorn', '~> 5.2'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'authority', '~> 3.2', '>= 3.2.2'
gem 'rolify', '~> 5.1'
gem 'rmagick', '~> 2.16'
gem 'nokogiri', '~> 1.7', '>= 1.7.0.1'

gem 'mini_magick', '~> 4.6'
gem 'mime-types', '~> 3.1'

gem 'sidekiq', '~> 4.2', '>= 4.2.9'

gem 'whenever', '~> 0.9.7', :require => false

gem 'state_machine', '~> 1.2'
gem 'state_machines', '~> 0.5.0'
# gem 'state_machines-audit_trail', '~> 2.0'
gem 'state_machines-audit_trail', '~> 1.0', '>= 1.0.2'

gem 'state_machines-mongoid', '~> 0.2.0'

# Use redis as session store
group :production do
  gem 'redis-store', '~> 1.3.0'
  gem 'redis-rails', '~> 5.0', '>= 5.0.1'
end

gem 'newrelic_rpm', '~> 3.15', '>= 3.15.2.317'

#for client side validations
gem 'client_side_validations', '~> 9.3', '>= 9.3.4'
gem 'client_side_validations-simple_form', '~> 6.3.0'
gem "jquery-validation-rails"
gem 'dicom', '~> 0.9.7'

gem 'high_voltage', '~> 3.0'
gem 'spreadsheet', '~> 1.1', '>= 1.1.4'

gem 'fog-aws', '~> 0.8.1'

gem 'gcm', '~> 0.1.1'
gem 'exception_notification', '~> 4.2', '>= 4.2.1'
gem 'jquery-fileupload-rails', '~> 0.4.7'
gem 'elasticsearch-model', '~> 0.1.9'
gem 'elasticsearch-rails', '~> 0.1.9'

# This gem loads environment variables as per your environments
gem 'dotenv-rails', '~> 2.2', '>= 2.2.1'

gem 'redis', '~> 3.3', '>= 3.3.3', :groups => [:development]

gem 'rails-assets-jquery-textcomplete', source: 'https://rails-assets.org'

gem 'aws-sdk', '~> 2.10.25'   #tHIS IS TO ACCESS AWS FOR RUBY

gem 'unicorn-worker-killer', '~> 0.4.4'

gem 'doorkeeper-mongodb', '~> 4.1'

gem 'rest-client', '~> 2.0', '>= 2.0.2'

#for times in different timezones
gem 'tzinfo', '~> 1.2', '>= 1.2.2'