field :correct_patient, type: String
  field :correct_procedure, type: String
  field :before_induction_valid_consent, type: String
  field :site_marked, type: String
  field :anesthesia_machine, type: String
  field :tourniquet_drills_suction, type: String
  field :implants_checked, type: String
  field :patient_allergy, type: String
  field :difficult_airway, type: String
  field :confirm_team_listed, type: String
  field :patient_checked, type: String
  field :valid_consent, type: String
  field :procedure_checked, type: String
  field :site_checked_and_marked, type: String
  field :imaging_checked, type: String
  field :antibiotic_prophylaxis_given, type: String
  field :xray_safety_check, type: String
  field :otchecklist_comments, type: String